[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true}
tokio = {workspace = true}
entity  = { path = "../entity" }